### PR TITLE
New assets

### PR DESCRIPTION
**Pull request by ghost**
Plz

### CODE REVIEW

**Comment by TheClashFruit** [comment]
no, i still dont like it

**Comment by iyxan23** [comment]
> no, i still dont like it
> 

no it looks cool

**Comment by TheClashFruit** [comment]
> > no, i still dont like it
> 
> no it looks cool

no, its a beehive

**Comment by TheClashFruit** [comment]
i like this i bit more, but sill that beehive aaa
Icon

**Comment by TheClashFruit** [comment]
its better like this
Icon

**Comment by TheClashFruit** [comment]
minimalist (I like it actually :sus:)
Icon (2)

**Comment by iyxan23** [comment]
Looks interesting, I have an idea where the logo maybe should look "Open" :hidepain:, so the top part of that cube would be hollow to say that "oh hey this cube is open, openblocks!"

**Comment by iyxan23** [comment]
So tcf made it (the hollow part should be a bit up)
image

**Comment by TheClashFruit** [comment]
@Iyxan23 here i think its perfect now
Icon (7)

**Comment by Tarochino** [comment]
Icon has changed

**Pull request closed without merging**
